<?php
/**
 * OrbitDesk — Accounting Export Helpers
 * Exports to Excel-compatible XLS (tab-separated), QuickBooks IIF, and standard CSV.
 * No Composer / no PHPSpreadsheet required — pure PHP.
 */

/**
 * Export transactions to a tab-separated .xls file (opens correctly in Excel).
 *
 * @param array  $transactions Rows from acc_transactions
 * @param array  $summary      Optional KPI summary [['label'=>'','value'=>'']]
 * @param string $filename     Download filename
 * @param string $orgName      Organization name for header
 */
function exportAccountingExcel(array $transactions, array $summary = [], string $filename = 'accounting-export.xls', string $orgName = ''): void {
    header('Content-Type: application/vnd.ms-excel');
    header('Content-Disposition: attachment; filename="' . rawurlencode($filename) . '"');
    header('Cache-Control: no-cache, must-revalidate');
    header('Pragma: no-cache');
    header('Expires: 0');

    $nl   = "\r\n";
    $tab  = "\t";
    $out  = '';

    // ── Header ──────────────────────────────────────────────────
    $out .= ($orgName ?: APP_NAME) . ' — Accounting Export' . $nl;
    $out .= 'Generated: ' . date('d M Y H:i') . $nl;
    $out .= $nl;

    // ── Summary ─────────────────────────────────────────────────
    if (!empty($summary)) {
        $out .= 'SUMMARY' . $nl;
        foreach ($summary as $s) {
            $out .= ($s['label'] ?? '') . $tab . ($s['value'] ?? '') . $nl;
        }
        $out .= $nl;
    }

    // ── Column headers ───────────────────────────────────────────
    $cols = ['Date', 'Transaction Type', 'Reference No', 'Account', 'Debit (KES)', 'Credit (KES)', 'Balance (KES)', 'Description', 'Narration / Memo'];
    $out .= implode($tab, $cols) . $nl;

    // ── Rows ─────────────────────────────────────────────────────
    $runBal = 0;
    foreach ($transactions as $t) {
        $type    = strtolower($t['type'] ?? $t['transaction_type'] ?? '');
        $amount  = (float)($t['amount'] ?? 0);
        $isDebit = in_array($type, ['debit','expense','payment','withdrawal']);
        $debit   = $isDebit ? number_format($amount, 2, '.', '') : '';
        $credit  = !$isDebit ? number_format($amount, 2, '.', '') : '';
        $runBal  += $isDebit ? -$amount : $amount;

        $row = [
            $t['date']        ?? '',
            ucfirst($type),
            $t['reference']   ?? $t['ref']           ?? '',
            $t['account_name'] ?? $t['account']       ?? '',
            $debit,
            $credit,
            number_format($runBal, 2, '.', ''),
            str_replace(["\t","\r","\n"], ' ', $t['description'] ?? $t['narration'] ?? ''),
            str_replace(["\t","\r","\n"], ' ', $t['notes']  ?? $t['memo']       ?? ''),
        ];
        $out .= implode($tab, $row) . $nl;
    }

    // ── Footer ───────────────────────────────────────────────────
    $out .= $nl;
    $out .= '-- End of export | Generated by ' . APP_NAME . ' | ' . APP_URL . ' --' . $nl;

    echo $out;
    exit;
}

/**
 * Export transactions to standard double-entry CSV.
 *
 * @param array  $transactions Rows from acc_transactions
 * @param string $filename
 */
function exportAccountingCSV(array $transactions, string $filename = 'transactions.csv'): void {
    header('Content-Type: text/csv; charset=UTF-8');
    header('Content-Disposition: attachment; filename="' . rawurlencode($filename) . '"');
    header('Cache-Control: no-cache');

    // UTF-8 BOM for Excel compatibility
    echo "\xEF\xBB\xBF";

    $fp = fopen('php://output', 'w');
    fputcsv($fp, ['Date', 'Type', 'Reference', 'Account', 'Debit', 'Credit', 'Balance', 'Description']);

    $runBal = 0;
    foreach ($transactions as $t) {
        $type    = strtolower($t['type'] ?? $t['transaction_type'] ?? '');
        $amount  = (float)($t['amount'] ?? 0);
        $isDebit = in_array($type, ['debit','expense','payment','withdrawal']);
        $runBal += $isDebit ? -$amount : $amount;

        fputcsv($fp, [
            $t['date']          ?? '',
            ucfirst($type),
            $t['reference']     ?? $t['ref']    ?? '',
            $t['account_name']  ?? $t['account'] ?? '',
            $isDebit  ? number_format($amount, 2, '.', '') : '',
            !$isDebit ? number_format($amount, 2, '.', '') : '',
            number_format($runBal, 2, '.', ''),
            $t['description'] ?? $t['narration'] ?? '',
        ]);
    }

    fclose($fp);
    exit;
}

/**
 * Export transactions in QuickBooks IIF (Intuit Interchange Format).
 * Compatible with QuickBooks Desktop import.
 *
 * @param array  $transactions Rows from acc_transactions
 * @param string $orgName      Company name shown in IIF header
 */
function exportQuickBooksIIF(array $transactions, string $orgName = ''): void {
    header('Content-Type: text/plain; charset=UTF-8');
    header('Content-Disposition: attachment; filename="quickbooks-import-' . date('Ymd') . '.iif"');
    header('Cache-Control: no-cache');

    $nl = "\r\n";
    $tab = "\t";

    // IIF headers
    echo '!TRNS' . $tab . 'TRNSID' . $tab . 'TRNSTYPE' . $tab . 'DATE' . $tab . 'ACCNT' . $tab . 'NAME' . $tab . 'AMOUNT' . $tab . 'MEMO' . $nl;
    echo '!SPL'  . $tab . 'SPLID'  . $tab . 'TRNSTYPE' . $tab . 'DATE' . $tab . 'ACCNT' . $tab . 'NAME' . $tab . 'AMOUNT' . $tab . 'MEMO' . $nl;
    echo '!ENDTRNS' . $nl;

    foreach ($transactions as $idx => $t) {
        $type   = strtolower($t['type'] ?? 'general journal');
        $qbType = match ($type) {
            'invoice', 'receipt' => 'INVOICE',
            'payment'            => 'PAYMENT',
            'expense'            => 'CHECK',
            'bill'               => 'BILL',
            default              => 'GENERAL JOURNAL',
        };
        $amount  = (float)($t['amount'] ?? 0);
        $isDebit = in_array($type, ['debit','expense','payment','withdrawal']);
        $iifAmt  = $isDebit ? -$amount : $amount;
        $date    = !empty($t['date']) ? date('m/d/Y', strtotime($t['date'])) : date('m/d/Y');
        $memo    = str_replace(["\t","\r","\n"], ' ', $t['description'] ?? $t['narration'] ?? '');
        $account = $t['account_name'] ?? $t['account'] ?? 'Unclassified';
        $ref     = $t['reference'] ?? $t['ref'] ?? '';

        echo 'TRNS' . $tab . ($idx+1) . $tab . $qbType . $tab . $date . $tab . $account . $tab . ($orgName ?: APP_NAME) . $tab . number_format($iifAmt, 2, '.', '') . $tab . $memo . $nl;
        echo 'SPL'  . $tab . ($idx+1) . $tab . $qbType . $tab . $date . $tab . $account . $tab . '' . $tab . number_format(-$iifAmt, 2, '.', '') . $tab . $ref . $nl;
        echo 'ENDTRNS' . $nl;
    }

    exit;
}
